[colors.primary]
background = "#000000"

[font]
size = 14

[font.bold]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.7
