theme = "solarized-dark"
icons = "awesome"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

# [[block]]
# block = "custom"
# cycle = ["bash -c 'data=`curl 127.0.0.1:8080/0/0`; echo \"$(echo $data | jq -r .data.hitokoto)--「$(echo $data | jq -r .data.from)」\"'"]
# interval = 30

[[block]]
block = "music"
max_width = 10
buttons = ["play", "next"]

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/woshiluo/.mail/woshiluo/Inbox", "/home/woshiluo/.mail/outlook/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "custom"
command = 'echo "树林里分出了两条路，而我，选择了人迹稀少的那条，那决定了一切的不同。 "'

[[block]]
block = "net"
format = "{speed_up;K*B} {speed_down;K*B}"
format_alt = "{ssid} {signal_strength}"
interval = 5
hide_missing = true
hide_inactive = true

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used} | {swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 1
format = "%a %Y/%m/%d %T"
