icons_format = "{icon}"

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"

# [[block]]
# block = "custom"
# cycle = ["bash -c 'data=`curl 127.0.0.1:8080/0/0`; echo \"$(echo $data | jq -r .data.hitokoto)--「$(echo $data | jq -r .data.from)」\"'"]
# interval = 30

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"
# interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/woshiluo/.mail/woshiluo/Inbox", "/home/woshiluo/.mail/outlook/Inbox", "/home/woshiluo/.mail/qq/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "custom"
command = "echo \"What we leave behind is not as important as how we've lived.\""

[[block]]
block = "net"
interval = 1
format = " $icon ^icon_net_down $speed_down.eng(prefix:Ki) ^icon_net_up $speed_up.eng(prefix:Ki) "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Gi)/$mem_total.eng(prefix:Gi) "
format_alt = " $icon $swap_used.eng(prefix:Gi)/$swap_total.eng(prefix:Gi) "
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:3) "

# [[block]]
# block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time} "

[[block]]
block = "custom"
command = '(systemctl --user is-active swayidle | grep inactive >/dev/null) && echo "" || echo "\uf023"'
interval = 5
[[block.click]]
button = "left"
cmd = '~/.config/scripts/toggle-idle.sh'

[[block]]
block = "time"
interval = 1
format.full = " $icon $timestamp.datetime(f:'%a %Y/%m/%d %T') "
