position = "top"
height = 25
icon_theme = "Papirus"

# [[end]]
# music_dir = '/home/woshiluo/Music'
# player_type = 'mpd'
# type = 'music'

# [end.truncate]
# max_length = 100
# mode = 'end'

[[end]]
type = "label"
class = "mail"
label = " {{ fd new ~/.mail | grep Inbox | xargs fd . | wc -l }}"

[[end]]
host = 'localhost:6600'
player_type = 'mpd'
truncate = 'end'
type = 'music'


[[end]]
type = 'sys_info'
format = [
    ' {cpu_percent}%',
    ' {memory_used} / {memory_total} GB',
#    '| {swap_used} / {swap_total} GB',
    ' {net_down:wlp2s0} / {net_up:wlp2s0} Mbps',
#    '猪 {load_average:1}',
]


[end.interval]
cpu = 1
memory = 1
networks = 1

[[end]]
type = 'custom'

[[end.bar]]
type = 'button'
label = '{{ (systemctl --user is-active hypridle | grep inactive >/dev/null) && echo "" || echo "" }}'
on_click = '!~/.config/scripts/toggle-idle.sh'

[[end]]
type = 'upower'
icon_size = 16

# [[end]]
# max_items = 3
# type = 'clipboard'
# 
# [end.truncate]
# length = 50
# mode = 'end'

[[end]]
type = 'clock'
format="%Y/%m/%d %a %H:%M:%S"

[[end]]
type = 'tray'

[[start]]
all_monitors = true
type = 'workspaces'
# favorites = ['1','2','3','4','5','6','7','8','9', '10']
# 
[[center]]
show_icon = false
type = 'focused'
